### PR TITLE
Add some required folders/packages and clean up node_modules

### PR DESCRIPTION
**Pull request by outlyer**
Just some minor changes to fix some issues I had with the package. 

* Remove ``node_modules`` from the source tree, since it is added by ```npm install```
* Add ``roonlabs/node-roon-api-volume-control`` to ``package.json`` as it is required to run the app as far as I can tell. 
* I needed an empty ``UPnP/Profiles`` folder or it could not write the HEOS device xml file. 

Other than these small changes, this worked perfectly, including hires audio.    

(Also, I use it with [pm2](https://www.npmjs.com/package/pm2) to keep it running.)

### CODE REVIEW

**Comment by LINVALE** [comment]
Thank you.

Agree.

Peter

**Comment by LINVALE** [comment]
New version about to be made avaialble.

**Comment by LINVALE** [comment]
Without a local node modules this fails for me.

Am I missing something in the way I have this set up?

**Comment by outlyer** [comment]
When you first install the app, you can run ``npm install`` to  populate the ``node_modules`` with the versions in ```package.json```. 

Please let me know if that isn't working for you as it seems to be working on my end.

**Comment by LINVALE** [comment]
Thanks.

Got it.  Just need to see what I need in the docker container.

Thanks for your help.

**Pull request merged**
